# Generated by Django 5.2 on 2025-05-14 20:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='check_in',
            new_name='check_in_date',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='check_out',
            new_name='check_out_date',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='food_charge',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='room_charge',
        ),
        migrations.AddField(
            model_name='bill',
            name='date_issued',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 5, 14, 20, 34, 14, 302108, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.customer'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
