# Generated by Django 5.2 on 2025-05-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_remove_bill_date_issued_bill_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='food_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='room_charge',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
