# Generated by Django 5.2 on 2025-05-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_bill_food_charge_alter_bill_room_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='food_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='bill',
            name='room_charge',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
