# Generated by Django 5.2 on 2025-05-22 12:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_alter_bill_room_charge_alter_bill_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotel.customer'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='food_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='room_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
